---

- name: setup maschinentuer.fftr
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

  roles:
    - raspbian-emu
    - tuer
